### ISSUE TITLE
Print out test results

### ISSUE THREAD

**Issue by ftiryaki** [akjindal53244/dependency_parsing_tf#4]
Hi,
How can we print out the test results as conll files, currently it only created the model and evaluates it, but there is no result conll.

Thank you

Firat

**Comment by akjindal53244** [comment]
Hi Firat,

Sorry for late response.

`compute_dependencies()` : takes cares of predicting dependency/head token for every `Token` in `Sentence`. From functionality point of view, it calls below two functions in a loop.

1. `update_child_dependencies()` : stores dependency and left/right child. updates the dependencies after every step of prediction so this predicted dependency can be used as feature to calculate dependency for next `Token`.

2. `update_state_by_transition()` : updates the state.

`update_child_dependencies()` and `update_state_by_transition()` are being called one after another so we can have updated state in `stack` as well as in `buff`, which will be used for next subsequent prediction. This process run in a loop. This code is available under `parser_model.py`. 


> How can we print out the test results as conll files, currently it only created the model and evaluates it, but there is no result conll.

class `DataReader` reads a conll file and stores various fields of this in class `Token`, thus every `Sentence` is list of `Token` objects.

You can iterate over `Token` objects and dump them into a file along with prediction. 

_How to get prediction?_
```
for h, t, in sentence.predicted_dependencies:
    head[t] = h
```

Hope that helps! :)
