### ISSUE TITLE
What dataset?

### ISSUE THREAD

**Issue by ningziwen** [akjindal53244/dependency_parsing_tf#5]
Hi,
Could you please tell me what dataset you use?
I just know the format is CONLL format but don't know where the dataset is from.
Sincerely,
Charlie

**Comment by akjindal53244** [comment]
Hi Ziwen,

It is "English Penn Treebank (PTB)". Please check Section-4 of [paper](https://cs.stanford.edu/~danqi/papers/emnlp2014.pdf). 

You can also download dataset from http://nlp.stanford.edu/~socherr/stanfordSentimentTreebank.zip
Hope it helps!


Regards,
Ashvini

**Comment by ningziwen** [comment]
Thank you!
